---
# tasks file for hostnames role

- name: hostnames | set node hostname
  hostname: name={{ role_hostnames_hostname_short }}
  tags:
    - hostname

- name: hostnames | add custom lines to /etc/hosts
  lineinfile: >
    dest=/etc/hosts
    line='{{ item }}'
    owner=root
    group=root
    mode=0644
  with_items: "{{ role_hostnames_etc_hosts_lines }}"
  notify: restart networking
  tags:
    - hostname
    - hostsfile
