---
# tasks file for networking

- name: networking | set node hostname
  hostname: name={{ role_networking_hostname_short }}
  tags:
    - hostname

- name: networking | add custom lines to /etc/hosts
  lineinfile: >
    dest=/etc/hosts
    line='{{ item }}'
    owner=root
    group=root
    mode=0644
  with_items: "{{ role_networking_etc_hosts_lines }}"
  notify: restart networking
  tags:
    - hostname
    - hostsfile
